### ISSUE TITLE
Make an auto-updater for the client

### ISSUE THREAD

**Issue by SylvKT** [Bash-09/tf2-bot-kicker-gui#10]

**Comment by Googe14** [comment]
I will definitely look into doing this in the future

**Comment by Bash-09** [comment]
It's not quite an auto-updater, but I have added a popup when the app starts if the latest release on github is a different version from what you are using along with links to download it quickly. I'm not sure people would be comfortable with the binary updating itself (or actually how that would work tbh) without the user's input, so I am satisfied with this solution.
