### ISSUE TITLE
Add a button to remove Steam ID of players marked as bots from active lists

### ISSUE THREAD

**Issue by obbyfus** [Bash-09/tf2-bot-kicker-gui#21]
Sometimes mistakes can be made, and players get marked and saved as bots. This is difficult for the user to know until one day in a casual match, a player complains that you are calling them out for being a bot and trying to kick them! 

Currently, the way to fix this is much too difficult, with the options of either marking the player as "not a bot" every single time they are in a server with the user, or checking the list manually in a text editor, and removing the name in question, which may not even be the same anymore due to name changes. As a consequence, the only way to remove the player would be to check all the Steam IDs manually until the player is found, and the ID can be removed.

It would be much more user friendly if there was a "Remove Steam ID" button equivalent to the "Save Steam ID" that is already a part of the bot kicker, as mistakes like these could be quickly and easily corrected.

**Comment by Bash-09** [comment]
Yes good point! I have had this issue myself even. I'm currently making some large changes that should resolve this issue, hopefully will not be too long until I release them.

**Comment by obbyfus** [comment]
Sounds great my man, Im very grateful to you for making this easily available on linux, because the more popular detectors are windows only

Also sorry for being super indecisive on the title

**Comment by Bash-09** [comment]
All g my friend, I play mainly on Linux so I understand the pain!

**Comment by Bash-09** [comment]
I've just added a new release, you will need to import your old play lists when you use the new version but it has much better control over saved accounts!
