### ISSUE TITLE
Allow importing PazerOP/tf2botdetector styles blocklists

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Bash-09/tf2-bot-kicker-gui#23]
Example : https://github.com/PazerOP/tf2_bot_detector/wiki/Customization#third-party-player-lists-and-rules
https://github.com/Critical-Cookie/TF2BD-ASEAN-LIST
https://github.com/qfoxb/tf2bd-lists

While your software works pretty great, UI-wise and all, I've noticed mine acted far inferior in a couple of games against actual other bot kicker player own protections.
I assume that it is due, to them, using default reported list of bots than the one set by default in this one.
I could parse those to view example bot lists and add it myself to the playerlist.json, but those have a different format and to be fair, I lack the knowledge to automatically parse only the UUID from them.

**Comment by Bash-09** [comment]
As long as the entries in the files use SteamID3 (the one that looks like U:1:123456) then you should be able to import them using `Import` -> `Import SteamIDs as Bots`

**Comment by PoorPocketsMcNewHold** [comment]
Even if those contain other bits ? As those filters contain other inforlation such as the type (which you can set on import in the app, indeed) name and other stuff.
I've tried with the second list playerlist.json file and imported it throught the app as bots. However, it didn't seemed to have added those entries to the Saved Players list.

**Comment by Bash-09** [comment]
It should just scrape the file for any SteamIDs and add them as bots or cheaters depending on what you chose. I haven't added anything to parse those files specifically so it is just limited to grabbing SteamIDs and adding them as a bot or cheater.

**Comment by PoorPocketsMcNewHold** [comment]
Thanks for the confirmation. I noticed that you said something along those lines in the release notes of the 1.2 version, but i wasn't sure if it was especially that.
