### ISSUE TITLE
kicker doesn't detect imposters that steal your name

### ISSUE THREAD

**Issue by SylvKT** [Bash-09/tf2-bot-kicker-gui#8]
![Screenshot from 2022-01-26 22-44-09](https://user-images.githubusercontent.com/18603248/151456969-7355fd3f-700d-4bb5-baab-86976a6e8a9e.png)
![20220126224348_1](https://user-images.githubusercontent.com/18603248/151457014-33677b74-304a-43f0-aaec-9fd631b52557.jpg)
![20220126224337_1](https://user-images.githubusercontent.com/18603248/151457023-67603356-6215-46f9-9135-0aef4d5b31bd.jpg)

![image](https://user-images.githubusercontent.com/18603248/151457992-c16373ad-5665-45a1-a12c-67e771063667.png)
this also happens sometimes with imposters

**Comment by Googe14** [comment]
I have considered checking if new players have copied the name of another player on the server, however it isn't uncommon that friends or groups of players might join with the same name for a bit of fun (e.g. "Engineer Gaming" etc). So in order to avoid false-positives I do not intend to check for duplicate names. Instead I recommend recording these players' steamIDs through the program manually if they are not automatically detected.

**Comment by TehcJS** [comment]
it didn't even put them on the list though when they copied my name

**Comment by Googe14** [comment]
What do you mean? They wouldn't show up in the player list or it didn't record them as bots into the recorded_bots.txt list?

It is an intended feature that another player with the same name as you is not recorded as a bot.

**Comment by TehcJS** [comment]
the ones with the `<player_name>?` name didn't show up at all in the player list.

**Comment by TehcJS** [comment]
no matter what

**Comment by Googe14** [comment]
Interesting, I will look into this and see if I can find the problem.

**Comment by TehcJS** [comment]
also, ones without the `?` don't get kicked at all. period.

**Comment by Googe14** [comment]
I cannot seem to recreate any issues with accounts connecting with duplicate names, for the most part those names are automatically prefixed with a number to make them stand out, and any duplicate named accounts that don't get matched by the regex are not intended to be identified as bots and kicked. 

If you encounter an issue with this and are able to screenshot an example I may be able to help some more,

**Comment by TehcJS** [comment]
there are bots that will steal your name without having a number before it.

**Comment by TehcJS** [comment]
i'll test this out in the new release when it comes out

**Comment by TehcJS** [comment]
so far, it has been attempting to kick imposter bots. i'll update if anything bad still happens.

**Comment by TehcJS** [comment]
The bot kicker has trouble identifying these bots for some reason. They don't even show up in the player list.
![Screenshot from 2022-01-26 22-44-09](https://user-images.githubusercontent.com/18603248/151456969-7355fd3f-700d-4bb5-baab-86976a6e8a9e.png)
![20220126224348_1](https://user-images.githubusercontent.com/18603248/151457014-33677b74-304a-43f0-aaec-9fd631b52557.jpg)
![20220126224337_1](https://user-images.githubusercontent.com/18603248/151457023-67603356-6215-46f9-9135-0aef4d5b31bd.jpg)

**Comment by TehcJS** [comment]
Also, why does it truncate my name half-way?

**Comment by TehcJS** [comment]
![image](https://user-images.githubusercontent.com/18603248/151457992-c16373ad-5665-45a1-a12c-67e771063667.png)
this also happens sometimes with imposters

**Comment by Googe14** [comment]
> Also, why does it truncate my name half-way?

I've made it truncate the names at a certain character limit so it doesn't overlap with the stuff on the right with default window size, maybe I will make it adjust with the window size.

**Comment by Googe14** [comment]
> ![image](https://user-images.githubusercontent.com/18603248/151457992-c16373ad-5665-45a1-a12c-67e771063667.png)
> this also happens sometimes with imposters

I'll try look into this in a little bit. I personally haven't encountered too many bots like this on the servers I play on so I may have to ask you for a little more, apologies. If you see these bots again could you please grab the output of the `status` command as well?

**Comment by TehcJS** [comment]
> > ![image](https://user-images.githubusercontent.com/18603248/151457992-c16373ad-5665-45a1-a12c-67e771063667.png)
> > this also happens sometimes with imposters
> 
> I'll try look into this in a little bit. I personally haven't encountered too many bots like this on the servers I play on so I may have to ask you for a little more, apologies. If you see these bots again could you please grab the output of the `status` command as well?
![20220127182055_1](https://user-images.githubusercontent.com/18603248/151459741-b1c12833-2030-4a9a-8131-61f63b7a6bb1.jpg)

**Comment by TehcJS** [comment]
It looks like that one fucks up the format of the player list

**Comment by TehcJS** [comment]
![20220127183924_1](https://user-images.githubusercontent.com/18603248/151461405-050a76ea-198c-4c8c-821a-f2240133a642.jpg)
![20220127183921_1](https://user-images.githubusercontent.com/18603248/151461410-a5ddc18c-a919-4eea-bb5a-68ca11cc8c31.jpg)
here's another instance of these question mark bots
it could be a normal imposter bot, though. i'm not sure

**Comment by TehcJS** [comment]
![image](https://user-images.githubusercontent.com/18603248/151467115-d073843d-83ab-4a6a-b279-07c65a849550.png)
alright, so anyone who has your name isn't added to the player list. don't check if someone is you by name

**Comment by Googe14** [comment]
That is very unusual, players are all handled by their SteamID in the program so I'm not sure why their name would cause a problem like this. I'll try and find the problem when I have time. 

Sorry to keep asking for things again, but if you come across them again could you get the output of both `status` and `tf_lobby_debug` as well?

**Comment by Bash-09** [comment]
Well after a long time I fixed the issues for accounts that have weird names or change them during gameplay. I did also add some name-steal detection but maybe too late, hopefully it isn't needed with Valve's patches.
